### ISSUE TITLE
Zendesk - Ticket priority highlight colors

### ISSUE THREAD

**Issue by joelthorner** [joelthorner/TLmanaGer#246]
### Todo list:
- [x] Refactor file to vanilla js & drop dependences
- [x] Documentation
- [x] Backend option (vue)
- [x] Help info (vue)

### Improvements:
- [x] Unification option onlyIncidents and colors with a card

### New functionalities:
- [x] None

### Other:
- [x] None
