### ISSUE TITLE
Logicommerce - beyond theme

### ISSUE THREAD

**Issue by joelthorner** [joelthorner/TLmanaGer#247]
### Todo list:
- [ ] Refactor file to vanilla js & drop dependences
- [ ] Documentation
- [x] Backend option (vue)
- [ ] Help info (vue)
- [ ] Theme 1 (cyberponk)

### Improvements:
- [ ] None

### New functionalities:
- [ ] None

### Other:
- [ ] None
