### ISSUE TITLE
Logicommerce - background

### ISSUE THREAD

**Issue by joelthorner** [joelthorner/TLmanaGer#248]
### Todo list:
- [x] Refactor file to vanilla js & drop dependences
- [x] Documentation
- [x] Backend option (vue)
- [x] Help info (vue)

### Improvements:
- [x] More LC background collections also with pagination
- [x] Added LC background on login screen

### New functionalities:
- [x] New undo action after change bg
- [x] More LC background collections also with pagination

### Other:
- [x] None
