### ISSUE TITLE
Logicommerce - developerBar

### ISSUE THREAD

**Issue by joelthorner** [joelthorner/TLmanaGer#249]
### Todo list:
- [x] Refactor file to vanilla js & drop dependences
- [x] Documentation
- [x] Backend option (vue)
- [x] Help info (vue)

### Improvements:
- [x] New design and icons
- [x] Improved search sync inputs

### New functionalities:
- [x] None

### Other:
- [x] Test into igd LC, cn LC and HK LC.
