### ISSUE TITLE
Logicommerce - pagesWindowBetter

### ISSUE THREAD

**Issue by joelthorner** [joelthorner/TLmanaGer#251]
### Todo list:
- [x] Refactor file to vanilla js & drop dependences
- [x] Documentation
- [x] Backend option (vue)
- [x] Help info (vue)

### Improvements:
- [x] Fixed page grid window when window is small.
- [x] Redesigned the "Grid pages" Logicommerce option to "Pages window better"

### New functionalities:
- [x] New suboption "Decorated page group headers"
- [x] New suboption "Page groups in grid mode"
- [x] New suboption "Better tree pages indentation"
- [x] Grouped all suboptions to "Pages window better" option

### Other:
- [x] None
