### ISSUE TITLE
Logicommerce - themeColors

### ISSUE THREAD

**Issue by joelthorner** [joelthorner/TLmanaGer#253]
### Todo list:
- [ ] Documentation
- [ ] Backend option (vue)
- [ ] Help info (vue)
- [x] Main and secondary colorpickers
- [ ] Colorpicker with image and filter hue-rotation

### Improvements:
- [ ] None

### Other:
- [x] None
