### ISSUE TITLE
fluidWebTools - flushRedisIgdDomain

### ISSUE THREAD

**Issue by joelthorner** [joelthorner/TLmanaGer#255]
### Todo list:
- [x] Refactor file to vanilla js & drop dependences
- [x] Documentation
- [x] Backend option (vue)
- [x] Help info (vue)
- [x] Tested in igd. urls

### Improvements:
- [x] None

### New functionalities:
- [x] None

### Other:
- [x] None
