### ISSUE TITLE
fluidWebTools - dumpAutoScroll

### ISSUE THREAD

**Issue by joelthorner** [joelthorner/TLmanaGer#256]
### Todo list:
- [x] Refactor file to vanilla js & drop dependences
- [x] Documentation
- [x] Backend option (vue)
- [x] Help info (vue)

### Improvements:
- [x] None

### New functionalities:
- [x] None

### Other:
- [x] None
