### ISSUE TITLE
Popup - containerLinesGuide

### ISSUE THREAD

**Issue by joelthorner** [joelthorner/TLmanaGer#262]
### Todo list:
- [x] Refactor file to vanilla js & drop dependences
- [x] Documentation
- [x] Popup  action (vue)
- [x] Popup cookie mark

### Improvements:
- [x] None

### New functionalities:
- [x] None

### Other:
- [x] None
